### ISSUE TITLE
Node script to import reddit JSON won't work

### ISSUE THREAD

**Issue by YonasBerhe** [openseattle/pulleykingcounty#1]
I want to import the reddit json thread into my mongodb local server, so I can begin analyzing it. Please help me out. 
> app.js file below

    var MongoClient = require('mongodb').MongoClient
      , request = require('request');
    
    MongoClient.connect('mongodb://localhost:27017/trasmatter', function(err, db) {
        if(err) throw err;
    request('https://www.reddit.com/r/Seattle/comments/3e0q5u/why_metro_matters_infographic/.json', function (error, response, body) {
        if (!error && response.statusCode == 200) {
            var obj = JSON.parse(body);

            var stories = obj.data.children.map(function (story) { return story.data; });

            db.collection('reddit').insert(stories, function (err, data) {
                    if(err) throw err;

                    console.dir(data);

                    db.close();
            });
        }
    });
    });

> Console error after running 'node app.js'

    app.js:11
                var stories = obj.data.children.map(function (story) { return sto
                                      ^
    TypeError: Cannot read property 'children' of undefined
        at Request._callback (/Users/yay/code/pulley/app.js:11:35)
        at Request.self.callback (/Users/yay/code/pulley/node_modules/request/request.js:198:22)
        at Request.emit (events.js:110:17)
        at Request.<anonymous> (/Users/yay/code/pulley/node_modules/request/request.js:1057:14)
        at Request.emit (events.js:129:20)
        at IncomingMessage.<anonymous> (/Users/yay/code/pulley/node_modules/request/request.js:1003:12)
        at IncomingMessage.emit (events.js:129:20)
        at _stream_readable.js:908:16
        at process._tickCallback (node.js:355:11)

> Another script file that works successfully. (I just plugged in
> another link and change localhost link)

    var MongoClient = require('mongodb').MongoClient
         , request = require('request');
      
       MongoClient.connect('mongodb://localhost:27017/course', function(err, db) {
           if(err) throw err;
      
           request('http://www.reddit.com/r/technology/.json', function (error, response, body) {
              if (!error && response.statusCode == 200) {
                  var obj = JSON.parse(body);
     
                 var stories = obj.data.children.map(function (story) { return story.data; });
     
                  db.collection('reddit').insert(stories, function (err, data) {
                          if(err) throw err;
     
                          console.dir(data);
     
                          db.close();
                 });

**Comment by loganfranken** [comment]
Hey @YonasBerhe!

It looks like https://www.reddit.com/r/Seattle/comments/3e0q5u/why_metro_matters_infographic/.json returns an array as the top-level JSON element, so I think changing this:

```
obj.data.children
```

To this:

```
obj[1].data.children
```

Should do the trick.

**Comment by YonasBerhe** [comment]
Awesome thanks man I was really pulling my hair over that one. Pushing new changes now.

**Comment by loganfranken** [comment]
Glad I could help!
